// Generated by terse actor generate; regenerate instead of editing.
/**
 * Add `terse-sdk` to your package.json dependencies: `npm install terse-sdk`.
 *
 * Use this file to call actors and prepare WebSocket access from your backend.
 * @example
 * import { actors, ActorProxy, type ActorAuthorization } from "./generated/index.js"
 */
import { createActorStub as $createActorStub, SocketProxy as $SocketProxy } from "terse-sdk/actors"
import type { ActorRpcTransport, ProxyActor, SocketGrant } from "terse-sdk/actors"


/**
 * Types for actor state and socket messages.
 * @example
 * type State = actors.Counter.State
 */
export declare namespace actors {
    export namespace Counter {
        export interface Metadata {
            userId: string
        }

        export interface Incoming {
            by: number
        }

        export interface Outgoing {
            count: number
        }

        export interface State {
            count: number
        }

        export interface Authorization {
            actorName: "Counter"
            actorId: string
            metadata: Metadata
            clientLocation?: { latitude: number; longitude: number }
            authorizationLifetimeMs?: number
        }
    }
}

/**
 * Types for actor state and methods.
 * @example
 * type State = actors.Counter.State
 */
export declare namespace actors {
    export namespace Counter {
        export type IncrementBy = number

        export type IncrementResult = number
        export interface Stub {
            increment(by?: IncrementBy): Promise<IncrementResult>
        }
        interface $MethodTypes {
            ["increment"]: {
                Args: Parameters<Stub["increment"]>
                Result: Awaited<ReturnType<Stub["increment"]>>
            }
        }
        export interface Methods extends $MethodTypes {}
        /**
         * Types for a method's arguments and return value.
         * @example
         * type Args = actors.Counter.Methods["increment"]["Args"]
         * type Result = actors.Counter.Methods["increment"]["Result"]
         */
        export namespace Methods {
            export namespace increment {
                export type Args = $MethodTypes["increment"]["Args"]
                export type Result = $MethodTypes["increment"]["Result"]
            }
        }
    }
}

/**
 * Call actor methods from your backend.
 * @example
 * const actor = actors.Counter.get("actor-id")
 */
export const actors = {
    ["Counter"]: {
        get(actorId: string, transport?: ActorRpcTransport): actors.Counter.Stub {
            return $createActorStub<actors.Counter.Stub>(
                "Counter",
                actorId,
                [{ name: "increment", result: "value" }],
                transport
            )
        },
        /**
         * Allow a frontend connection after your backend checks the user's access.
         * @example
         * const grant = await actors.Counter.prepareWebsocket({ actorId: "actor-id", metadata })
         */
        prepareWebsocket(
            authorization: { actorId: string; metadata: actors.Counter.Metadata; authorizationLifetimeMs?: number }
        ): Promise<SocketGrant> {
            return new ActorProxy().handle({ ...authorization, actorName: "Counter" })
        }
    }
}

/**
 * The actor and connection details approved by your backend.
 * @example
 * const authorization: ActorAuthorization = { actorName: "Counter", actorId: "actor-id", metadata }
 */
export type ActorAuthorization = actors.Counter.Authorization

/**
 * Allow a frontend connection after your backend checks the user's access.
 * @example
 * const grant = await ActorProxy.handle({ actorName: "Counter", actorId: "actor-id", metadata })
 */
export class ActorProxy extends $SocketProxy<{
    ["Counter"]: ProxyActor<actors.Counter.Metadata>
}> {
    constructor(
        
    ) {
        super(
            { ["Counter"]: {} as ProxyActor<actors.Counter.Metadata> }
        )
    }

    handle(authorization: ActorAuthorization): Promise<SocketGrant> {
        return super.handle(authorization)
    }

    static handle(
        authorization: ActorAuthorization
    ): Promise<SocketGrant> {
        return new ActorProxy().handle(authorization)
    }
}
